### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajghadi1**

### CODE REVIEW

**Comment by kb22** [comment]
Adding additional text does not add much information to the README. Include the list of packages as a list, their version numbers, correct names and more.

**Comment by rajghadi1** [comment]
Sorry brother I did this because I participate in hactober fest and there
they tell us to send pull request but i dont have much programing knowledge
as like you, sorry again for this.

**Comment by kb22** [comment]
I believe then you are not interested in making any updates so I'm closing this pull request without merging.

**Comment by rajghadi1** [comment]
its ok

**Pull request closed without merging**
